spring:
  profiles:
    active: dev
  mvc:
    format:
      date: dd/MM/yyyy
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zsp.pojo
  configuration:
    map-underscore-to-camel-case: true